"""initial

Revision ID: d077ecb1a4cc
Revises: 
Create Date: 2026-03-25 14:19:20.007002

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd077ecb1a4cc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artists',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('spotify_id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('genres', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('popularity', sa.Integer(), nullable=True),
    sa.Column('follower_count', sa.Integer(), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('spotify_id')
    )
    with op.batch_alter_table('artists', schema=None) as batch_op:
        batch_op.create_index('ix_artists_spotify_id', ['spotify_id'], unique=False)

    op.create_table('global_snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('playlist_id', sa.String(length=100), nullable=False),
    sa.Column('country_code', sa.String(length=10), nullable=True),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('avg_valence', sa.Float(), nullable=True),
    sa.Column('avg_energy', sa.Float(), nullable=True),
    sa.Column('avg_danceability', sa.Float(), nullable=True),
    sa.Column('avg_tempo', sa.Float(), nullable=True),
    sa.Column('top_genres', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('track_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('global_snapshots', schema=None) as batch_op:
        batch_op.create_index('ix_gls_country_date', ['country_code', 'snapshot_date'], unique=False)

    op.create_table('tracks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('spotify_id', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('album', sa.String(length=500), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('popularity', sa.Integer(), nullable=True),
    sa.Column('release_year', sa.Integer(), nullable=True),
    sa.Column('preview_url', sa.String(length=500), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('spotify_id')
    )
    with op.batch_alter_table('tracks', schema=None) as batch_op:
        batch_op.create_index('ix_tracks_popularity', ['popularity'], unique=False)
        batch_op.create_index('ix_tracks_release_year', ['release_year'], unique=False)
        batch_op.create_index('ix_tracks_spotify_id', ['spotify_id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('artist_follower_snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('artist_id', sa.UUID(), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('follower_count', sa.Integer(), nullable=True),
    sa.Column('chart_position', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['artist_id'], ['artists.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('artist_follower_snapshots', schema=None) as batch_op:
        batch_op.create_index('ix_afs_artist_date', ['artist_id', 'snapshot_date'], unique=False)

    op.create_table('audio_features',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('track_id', sa.UUID(), nullable=False),
    sa.Column('energy', sa.Float(), nullable=True),
    sa.Column('valence', sa.Float(), nullable=True),
    sa.Column('danceability', sa.Float(), nullable=True),
    sa.Column('acousticness', sa.Float(), nullable=True),
    sa.Column('instrumentalness', sa.Float(), nullable=True),
    sa.Column('liveness', sa.Float(), nullable=True),
    sa.Column('speechiness', sa.Float(), nullable=True),
    sa.Column('tempo', sa.Float(), nullable=True),
    sa.Column('key', sa.Integer(), nullable=True),
    sa.Column('time_signature', sa.Integer(), nullable=True),
    sa.Column('loudness', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('track_id')
    )
    op.create_table('compatibility_cache',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_a_id', sa.UUID(), nullable=False),
    sa.Column('user_b_id', sa.UUID(), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('breakdown', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('computed_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_a_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_b_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('compatibility_cache', schema=None) as batch_op:
        batch_op.create_index('ix_cc_user_pair', ['user_a_id', 'user_b_id'], unique=False)

    op.create_table('genre_snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('snapshot_month', sa.Date(), nullable=False),
    sa.Column('genre_distribution', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('mood_vector', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'snapshot_month', name='uq_genre_snapshot_user_month')
    )
    with op.batch_alter_table('genre_snapshots', schema=None) as batch_op:
        batch_op.create_index('ix_gs_user_month', ['user_id', 'snapshot_month'], unique=False)

    op.create_table('listening_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('track_id', sa.UUID(), nullable=False),
    sa.Column('played_at', sa.DateTime(), nullable=False),
    sa.Column('ms_played', sa.Integer(), nullable=True),
    sa.Column('context_type', sa.String(length=50), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('is_new_discovery', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('listening_history', schema=None) as batch_op:
        batch_op.create_index('ix_lh_user_played', ['user_id', 'played_at'], unique=False)
        batch_op.create_index('ix_lh_user_track', ['user_id', 'track_id'], unique=False)

    op.create_table('spotify_accounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('spotify_id', sa.String(length=100), nullable=False),
    sa.Column('encrypted_refresh_token', sa.Text(), nullable=False),
    sa.Column('country', sa.String(length=10), nullable=True),
    sa.Column('product', sa.String(length=20), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('spotify_id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('track_artists',
    sa.Column('track_id', sa.UUID(), nullable=False),
    sa.Column('artist_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['artists.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('track_id', 'artist_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('track_artists')
    op.drop_table('spotify_accounts')
    with op.batch_alter_table('listening_history', schema=None) as batch_op:
        batch_op.drop_index('ix_lh_user_track')
        batch_op.drop_index('ix_lh_user_played')

    op.drop_table('listening_history')
    with op.batch_alter_table('genre_snapshots', schema=None) as batch_op:
        batch_op.drop_index('ix_gs_user_month')

    op.drop_table('genre_snapshots')
    with op.batch_alter_table('compatibility_cache', schema=None) as batch_op:
        batch_op.drop_index('ix_cc_user_pair')

    op.drop_table('compatibility_cache')
    op.drop_table('audio_features')
    with op.batch_alter_table('artist_follower_snapshots', schema=None) as batch_op:
        batch_op.drop_index('ix_afs_artist_date')

    op.drop_table('artist_follower_snapshots')
    op.drop_table('users')
    with op.batch_alter_table('tracks', schema=None) as batch_op:
        batch_op.drop_index('ix_tracks_spotify_id')
        batch_op.drop_index('ix_tracks_release_year')
        batch_op.drop_index('ix_tracks_popularity')

    op.drop_table('tracks')
    with op.batch_alter_table('global_snapshots', schema=None) as batch_op:
        batch_op.drop_index('ix_gls_country_date')

    op.drop_table('global_snapshots')
    with op.batch_alter_table('artists', schema=None) as batch_op:
        batch_op.drop_index('ix_artists_spotify_id')

    op.drop_table('artists')
    # ### end Alembic commands ###
